### ISSUE TITLE
Чанки не прогружаются после любого измерения с мода Dimensional Doors

### ISSUE THREAD

**Issue by W1ry** [blutoo/techvsmagic#1]
Логи:
"IO-Worker-52" daemon prio=1 Id=413 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@881daa0
	at java.base@17.0.10/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@881daa0
	at java.base@17.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.10/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
	at java.base@17.0.10/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)

"Chunk Render Task Executor #0" prio=3 Id=429 WAITING on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Object.java:338)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.getNextJob(ChunkBuilder.java:265)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:318)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)

"Chunk Render Task Executor #1" prio=3 Id=430 WAITING on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Object.java:338)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.getNextJob(ChunkBuilder.java:265)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:318)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)

"Chunk Render Task Executor #2" prio=3 Id=431 WAITING on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Object.java:338)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.getNextJob(ChunkBuilder.java:265)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:318)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)

"Chunk Render Task Executor #3" prio=3 Id=432 WAITING on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Object.java:338)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.getNextJob(ChunkBuilder.java:265)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:318)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)

"Chunk Render Task Executor #4" prio=3 Id=433 WAITING on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Object.java:338)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.getNextJob(ChunkBuilder.java:265)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:318)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)

"Chunk Render Task Executor #5" prio=3 Id=434 WAITING on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@6e801140
	at java.base@17.0.10/java.lang.Object.wait(Object.java:338)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.getNextJob(ChunkBuilder.java:265)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:318)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)

[19:59:44] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:45] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:46] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:47] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:48] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:49] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:50] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:51] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:52] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:53] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:54] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:55] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:56] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:57] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:58] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?
[19:59:59] [Physics thread/WARN]: Too many physics frames in the physics frame queue. Is the game stage broken?

**Comment by blutoo** [comment]
такой баг вызывается из-за конфликта модов Valkyrien skies и Dimensonal Doors. временное решение - исключение из сборки одного из модов, до времени пока я найду способ восстановить совместимость.
