### ISSUE TITLE
Сборка не запускается

### ISSUE THREAD

**Issue by imfakeheart** [blutoo/techvsmagic#5]
Когда загрузка мира доходит до 100%, происходит это:

```
---- Minecraft Crash Report ----
// Don't do that.
Time: 2024-11-19 00:13:27
Description: mouseClicked event handler
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_2539
at knot//net.minecraft.class_310.method_29610(class_310.java:2087)
at knot//net.minecraft.class_7196.method_41889(class_7196.java:100)
at knot//net.minecraft.class_525.method_41847(class_525.java:326)
at knot//net.minecraft.class_7196.method_41892(class_7196.java:247)
at knot//net.minecraft.class_525.method_2736(class_525.java:310)
at knot//net.minecraft.class_525.method_19922(class_525.java:260)
at knot//net.minecraft.class_4185.method_25306(class_4185.java:43)
at knot//net.minecraft.class_4264.method_25348(class_4264.java:16)
at knot//net.minecraft.class_339.method_25402(class_339.java:120)
at knot//net.minecraft.class_4069.method_25402(class_4069.java:27)
at knot//net.minecraft.class_312.method_1611(class_312.java:94)
at knot//net.minecraft.class_437.method_25412(class_437.java:489)
at knot//net.minecraft.class_312.method_1601(class_312.java:94)
at knot//net.minecraft.class_312.method_22686(class_312.java:165)
at knot//net.minecraft.class_1255.execute(class_1255.java:103)
at knot//net.minecraft.class_312.method_22684(class_312.java:165)
at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
at knot//org.lwjgl.system.JNI.invokeV(Native Method)
at knot//org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
at knot//com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
at knot//net.minecraft.class_310.method_1523(class_310.java:1208)
at knot//net.minecraft.class_310.method_1514(class_310.java:768)
at knot//net.minecraft.client.main.Main.method_44604(Main.java:244)
at knot//net.minecraft.client.main.Main.main(Main.java:51)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2703 failed [in thread "Netty Local Client IO #0"]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
at knot//net.minecraft.class_2539.<clinit>(class_2539.java:267)
at knot//net.minecraft.class_2535.channelActive(class_2535.java:98)
at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
at knot//io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
at knot//io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
at knot//io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
at knot//io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
at knot//io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185)
at knot//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at knot//io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
at knot//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
at knot//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at java.base/java.lang.Thread.run(Thread.java:833)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
at knot//net.minecraft.class_310.method_29610(class_310.java:2087)
at knot//net.minecraft.class_7196.method_41889(class_7196.java:100)
at knot//net.minecraft.class_525.method_41847(class_525.java:326)
at knot//net.minecraft.class_7196.method_41892(class_7196.java:247)
at knot//net.minecraft.class_339.method_25402(class_339.java:120)
at knot//net.minecraft.class_4069.method_25402(class_4069.java:27)
at knot//net.minecraft.class_312.method_1611(class_312.java:94)
World Generation: Stable
```

**Comment by HyperPaint** [comment]
+1

**Comment by MrMedysa** [comment]
Удали levelZ
Установи fabric 0.18.1
Поменяй cloth config на версию 8.2.88
